spring:
  application:
    name: user-service
server:
  port: 8088

# Management \u914D\u7F6E
management:
  server:
    port: 8081
  endpoint:
    env:
      post:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      basePath: /management
    jmx:
      exposure:
        include: '*'

  spring:
    jmx:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12345/eureka
    registryFetchIntervalSeconds: 10